# permissions for end users to view spannerautoscalers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spannerautoscaler-viewer-role
rules:
- apiGroups:
  - spanner.mercari.com
  resources:
  - spannerautoscalers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - spanner.mercari.com
  resources:
  - spannerautoscalers/status
  verbs:
  - get
